petitions/config/routes.rb
Rails.application.routes.draw do

  root   "home#index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions
  resources :petitions
  resources :votes

end

petitions/app/models/petition.rb
class Petition < ActiveRecord::Base
  belongs_to :user   
end

petitions/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :petitions

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end  
end

petitions/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :petition
end

petitions/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_url, alert: "Вы не авторизованы" if current_user.nil?
  end
end

petitions/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
    @petitions = Petition.order(created_at: :desc).limit(10)
  end  
end

petitions/app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_action :authorize, only: [:new, :create]

  def index
    @petitions = Petition.all
    @petitions = @petitions.where(user: current_user) if params[:my]
  end

  def show
    @petitions = Petition.find(params[:id])
  end

  def edit
    petition = Petition.find(params[:id])
  end

  def update
    petition = Petition.find(params[:id])
    if petition.update(petition_params)
      redirect_to petition_path
    else
      render 'edit'
    end
  end

  def create
    petition = Petition.create(petition_params.merge({user_id: current_user.id}))
    if petition.save
      redirect_to petition_path(petition)
    else
      render 'new'
    end
  end

  def new
    @petitions = Petition.new
  end

  def destroy
    petition = Petition.find(params[:id])
    petition.destroy
    flash["alert-success"] = 'Петиция удалена'
    redirect_to petitions_path
  end

  private

  def petition_params
    params.require(:petition).permit(:title, :text)
  end
end

petitions/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.auth(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Добро пожаловать!"
    else
      flash.now.alert = "Email или пароль не верный"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

petitions/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to root_url, :notice => "Добро пожаловать!"
    else
      render "new"
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

petitions/app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

petitions/app/helpers/application_helper.rb
module ApplicationHelper
end

petitions/app/helpers/home_helper.rb
module HomeHelper
end

petitions/app/helpers/petitions_helper.rb
module PetitionsHelper
end

petitions/app/helpers/sessions_helper.rb
module SessionsHelper
end

petitions/app/helpers/users_helper.rb
module UsersHelper
end

petitions/app/helpers/votes_helper.rb
module VotesHelper
end

petitions/app/views/home/index.html.erb
<h2>Последние петиции</h2>

<table class="table">
  <thead>
  <tr>
    <th>Петиция</th>
    <th>Автор</th>
  </tr>
  </thead>
  <% @petitions.each do |petition| %>
    <%= render 'petitions/petition', petition: petition %>
  <% end %>
</table>

petitions/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petitions</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
  <% end %>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or 
    <%= link_to "Log in", log_in_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

petitions/app/views/petitions/_my.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Петиция</th>
      <th>Дата создания</th>
      <th>Действия</th>
    </tr>
  </thead>
  <% @petitions.each_with_index do |petition, index| %>
  <tr>
    <td><%= link_to petition.title, "petitions/#{index+1}" %></td>
    <td><%= petition.created_at.strftime("%d/%m/%Y %H:%M") %></td>
    <td><%= link_to "Редактировать", petition_path(petition), method: :patch %>
    <%= link_to "Удалить", petition_path(petition), method: :delete, data: { confirm: 'Уверены?' } %></td>
  </tr>
  <% end %>
</table>

petitions/app/views/petitions/edit.html.erb
<div style="margin: 15px">
  <h2>Новая Петиция</h2>
</div>

<%= form_for @petitions do |f| %>
  <% if @petitions.errors.any? %>

    <div>
      <h2>Form is invalid</h2>
      <ul>
        <% @petitions.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div style="margin: 15px">
    <div class="form-group" style="width: 40%">
      <%= f.label :title, 'Название' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 40%">
      <%= f.label :text, 'Описание' %><br />
      <%= f.text_area :text, class: 'form-control', rows: '6' %>
    </div>
    <div class="actions"><%= submit_tag "Обновить", class: 'btn btn-default' %></div>
  </div>

<% end %>

petitions/app/views/petitions/index.html.erb
<h2><%= params[:my] ? 'Мои' : 'Все' %> петиции</h2>

<% if params[:my] %>
  <%= render "my" %>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Петиция</th>
        <th>Автор</th>
        <th>Дата создания</th>
      </tr>
    </thead>
    <% @petitions.each_with_index do |petition, index| %>
    <tr>
      <td><%= link_to petition.title, "petitions/#{petition.id}" %></td>
      <td><%= petition.user.first_name + " " + petition.user.last_name %></td>
      <td><%= petition.created_at.strftime("%d/%m/%Y %H:%M") %></td>
    </tr>
    <% end %>
  </table>
<% end %>

petitions/app/views/petitions/new.html.erb
<h1>Новая Петиция</h1>
<%= form_for :petition, url: petitions_path do |f| %>

  <% if @petition.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@petition.errors.count, "error") %> prohibited
        this petition from being saved:
      </h2>
      <ul>
        <% @petition.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label :title, 'Название' %><br />
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Описание' %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= submit_tag 'Cоздать', class: 'btn btn-success' %>
  </div>
<% end %>

petitions/app/views/petitions/show.html.erb
<div style="margin: 15px">
  <h2><%= @petitions.title %></h2>
</div>
<div style="margin: 30px">
  <%= @petitions.text %>
</div>

petitions/app/views/users/new.html.erb
<h1>Регистрация</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" style="width: 50%">
    <%= f.label :email %><br />
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group" style="width: 50%">
    <%= f.label :first_name, 'Имя'%><br />
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group" style="width: 50%">
    <%= f.label :last_name, "Фамилия" %><br />
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group" style="width: 50%">
    <%= f.label :password, 'Пароль' %><br />
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group" style="width: 50%">
    <%= f.label :password_confirmation, 'Подтверждение пароля' %><br />
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="actions"><%= f.submit "Зарегистрироваться", class: 'btn btn-primary' %></div>
<% end %>